apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  # Cloud-neutral: binds to the default StorageClass
  # AKS -> Azure Disk; EKS -> gp2/gp3 EBS
  storageClassName: ""
