name: Infra + App Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'k8s/**'
      - 'app/**'
      - '.github/workflows/deploy.yml'

jobs:
  terraform:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[terraform]') || contains(join(github.event.commits.*.modified, ','), 'infra/')
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd infra
          terraform init

      - name: Terraform Apply
        run: |
          cd infra
          terraform apply -auto-approve

  app-deploy:
    name: Build and Deploy App
    runs-on: ubuntu-latest
    needs: [terraform] # Ensure infra is ready before deploy
    steps:
      - uses: actions/checkout@v4

      # Build & Push Docker image
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }} ./app
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}

      # Deploy to AKS
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/myapp myapp=${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }} -n default
          kubectl apply -f k8s/
